# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730e448f9b55b711ab3e7e9e98a5e7ec3dd2de0f9cdf46969a18bbe6ae3eade96e678477a22cd8cda0c623b4e19aa6f514621ddac15395a28d68fa9e20da4ec9

test:
  secret_key_base: c11a900d13ea4b324e2f9eb5660ad032397e96b4cf7b8a1a5881295666e98b8543c095b7029a04a4396d37e986298ad852766ff5a821b88327b775268dc36999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
